{"source": "exploit-database", "filename": "platforms/multiple/remote/39569.py", "cves": ["CVE-2016-3115"]}